version: '3.8'
services:
  weightgurus:
    image: ghcr.io/faisal-memon/weightgurus:latest
    env_file: .env
    environment:
      - WG_CSV_FILE=/output/weights.csv
      - TZ=America/Los_Angeles
    volumes:
      - ./output:/output
    restart: unless-stopped
