services:
  weightgurus:
    image: ghcr.io/faisal-memon/weightgurus:latest-local
    env_file: .env
    environment:
      - TZ=America/Los_Angeles
      - WG_UPDATE_INTERVAL=${WG_UPDATE_INTERVAL:-24h}
      - WG_JITTER_SECONDS_MAX=${WG_JITTER_SECONDS_MAX:-300}
    volumes:
      - ${WG_HOST_OUTPUT_DIR}:/output
    restart: unless-stopped
